Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2023
Var
// Seção de Declarações das variáveis 
ano:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Em que ano estamos?")
Leia(ano)
escreva("Estamos no ano de")
escreva(ano)

Fimalgoritmo