Algoritmo "Estrutura de repetição"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : UNIFAA
// Descrição   : Estrutura de repetição
// Autor(a)    : Guilherme Proença Corrêa
// Data atual  : 10/03/2023
Var
   // Seção de Declarações das variáveis
   i:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i:=0
   repita
      escreva(i)
      i:=i+1
   ate i>10 //Quando for verdadeiro o laço termina

Fimalgoritmo