Algoritmo "Função RANDI"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Gera números aleatórios
// Autor(a)    : Guilherme Proença Corrêa
// Data atual  : 10/03/2023
Var
// Seção de Declarações das variáveis 
i, numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 15 faca
 numero:= randi(26)
 escreva(numero)
fimpara

Fimalgoritmo