Algoritmo "Unidede 8 (Randi)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : UNIFAA
// Descrição   : RANDI
// Autor(a)    : Guilherme Proença Corrêa
// Data atual  : 11/03/2023
Var
// Seção de Declarações das variáveis 
x:inteiro
x1:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("X em rand(5)")
x1:=rand(5)
escreval(x1)
escreval("X em randi(5)")
x:=randi(5)
escreval(x)

Fimalgoritmo