Algoritmo "Unidade 10 (iten avaliativo)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : UNIFAA
// Descrição   :
// Autor(a)    : Guilherme Proença Corrêa
// Data atual  : 11/03/2023
Var
// Seção de Declarações das variáveis 
i,z,k:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para k de 1 ate 20 faca
i:=z+k
z:=z+1
fimpara
escreva(i)


Fimalgoritmo